services:
  site:
    build: .
    container_name: zuxi-site
    restart: unless-stopped
    ports:
      - "3847:80"
    networks:
      - web
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "reproxy.server=zuxi.mpanin.me"
      - "reproxy.route=^/(.*)"
      - "reproxy.dest=/$1"
      - "reproxy.port=80"
      - "reproxy.keep-host=true"

networks:
  web:
    external: true
